stages:
  - build
  - deploy

variables:
  # Aquí puedes agregar variables de entorno, como el nombre de la imagen
  IMAGE_NAME: "my-angular-app"

# Job de Build: Construir la aplicación Angular y la imagen Docker
build:
  stage: build
  image: node:21 # Usa una imagen de Node para construir la app
  script:
    - npm install    # Instalar dependencias
    - npm run build  # Construir la aplicación
    - docker build -t $IMAGE_NAME .  # Construir la imagen Docker
  only:
    - master  # Este job solo se ejecuta cuando se hace un push a la rama principal

# Job de Deploy: Desplegar la aplicación usando Nginx
deploy:
  stage: deploy
  image: nginx:alpine  # Utiliza la imagen de Nginx
  script:
    - docker run -d -p 80:80 $IMAGE_NAME  # Levanta el contenedor con Nginx
  only:
    - main  # Este job solo se ejecuta cuando se hace un push a la rama principal

